name: app_rhyme
description: "A Powerful CrossPlatform Music App Made By Flutter and Rust"
publish_to: "none"
version: 2.0.1
environment:
  sdk: ">=3.3.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  rust_lib_app_rhyme:
    path: rust_builder
  cupertino_icons: ^1.0.6
  flutter_rust_bridge: 2.8.0
  interactive_slider:
    git: https://github.com/canxin121/interactive_slider
  dismissible_page: ^1.0.2
  get: ^4.6.6
  audio_service: ^0.18.13
  infinite_scroll_pagination: ^4.0.0
  path_provider: ^2.1.3
  image_picker: ^1.1.0
  chinese_font_library: ^1.1.0
  dart_eval: ^0.7.9
  file_picker: ^8.0.3
  flutter_lyric:
    git: https://github.com/canxin121/flutter_lyric
  talker: ^4.1.5
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.19
  talker_flutter: ^4.1.5
  pull_down_button: ^0.10.1
  glassmorphism_ui: ^0.3.0
  toastification: ^2.0.0
  synchronized: ^3.3.0+3
  # just_audio的实现库
  just_audio_media_kit: ^2.0.0
  # just_audio的实现库just_audio_media_kit的linux实现
  media_kit_libs_linux: any
  # just_audio的实现库just_audio_media_kit的windows实现
  media_kit_libs_windows_audio: any
  just_audio: ^0.9.38
  # just_audio_windows:
  #   git:
  #     url: https://github.com/bdlukaa/just_audio_windows
  #     path: just_audio_windows
  package_info_plus: ^8.0.0
  drag_select_grid_view: ^0.6.2
  extended_image: ^9.1.0
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  flutter_exit_app: ^1.1.3
  back_button_interceptor: ^8.0.3
  reorderables: ^0.6.0
  flutter_keyboard_visibility: ^6.0.0
  bitsdojo_window: ^0.1.6
  glossy: ^0.0.4
  aura_box: ^1.0.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  package_rename: ^1.7.1
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: "assets/log-0.1.0.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    macos:
      enable: true

package_rename_config:
  android:
    app_name: AppRhyme
    package_name: canxin.app.rhyme

  ios:
    app_name: AppRhyme
    bundle_name: AppRhyme
    package_name: canxin.app.rhyme

  linux:
    app_name: AppRhyme
    package_name: canxin.app.rhyme
    exe_name: AppRhyme

  macos:
    app_name: AppRhyme
    package_name: com.canxin.AppRhyme
    copyright_notice: Copyright ©️ 2024 Canxin121. All rights reserved.

  windows:
    app_name: AppRhyme
    organization: Canxin
    exe_name: AppRhyme

flutter:
  uses-material-design: true

  assets:
    - assets/
